# Generated by Django 2.2.5 on 2019-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_mais',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='static\\img'),
        ),
    ]
